---
title: Persian language in its latin script
timezone: France/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
author: Language planning committee, FIAS.
simple_search: http://google.com/search
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
permalink: "/articles/:short_year/:title"
excerpt_separator: "<!--more-->"
exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- UploadToGithub.Rakefile
- README.md
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
